/* ProcureMarket browser client. Configure public Supabase values in supabase-config.js. */
const config = window.PROCUREMARKET_CONFIG || {};
let supabase, currentUser, currentProfile;
const page = location.pathname.split('/').pop() || 'index.html';
const protectedPages = {'business-dashboard.html':'business','business-profile.html':'business','create-tender.html':'business','view-bids.html':'business','supplier-dashboard.html':'supplier','supplier-profile.html':'supplier','submit-bid.html':'supplier'};
function setYear(){document.querySelectorAll('.year').forEach(e=>e.textContent=new Date().getFullYear())}
function esc(v=''){const e=document.createElement('div');e.textContent=v;return e.innerHTML}
function money(v){return new Intl.NumberFormat('en-JM',{style:'currency',currency:'JMD'}).format(Number(v))}
function fmtDate(v){return new Intl.DateTimeFormat('en-JM',{dateStyle:'medium'}).format(new Date(`${v}T00:00:00`))}
function message(text,type='success'){let b=document.getElementById('appMessage');if(!b){b=document.createElement('div');b.id='appMessage';document.querySelector('main')?.prepend(b)}b.className=`notice ${type==='error'?'error':''}`;b.textContent=text}
function busy(f,on){const b=f.querySelector('button');if(b){b.disabled=on;b.dataset.label||=b.textContent;b.textContent=on?'Please wait…':b.dataset.label}}
function configured(){return /^https:\/\/.+\.supabase\.co$/.test(config.url||'')&&(config.anonKey||'').length>40}
async function signedUrl(bucket,path){if(!path)return null;const{data,error}=await supabase.storage.from(bucket).createSignedUrl(path,300);return error?null:data.signedUrl}
async function upload(bucket,file){if(!file?.size)return null;if(file.size>10*1024*1024)throw new Error('Documents must be 10 MB or smaller.');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_'),path=`${currentUser.id}/${crypto.randomUUID()}-${safe}`;const{error}=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type});if(error)throw error;return{path,name:file.name}}
async function getSession(){const{data:{session}}=await supabase.auth.getSession();currentUser=session?.user||null;if(currentUser){const{data}=await supabase.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();currentProfile=data}}
function updateAuthUi(){document.querySelectorAll('a[href="login.html"]').forEach(a=>{if(currentUser){a.textContent='Log out';a.href='#';a.dataset.logout='true'}});document.querySelectorAll('a[href="register.html"]').forEach(a=>{if(currentUser)a.classList.add('hidden')});document.querySelectorAll('[data-logout]').forEach(a=>a.addEventListener('click',async e=>{e.preventDefault();await supabase.auth.signOut();location.href='index.html'}))}
function enforceAccess(){const role=protectedPages[page];if(!role)return true;if(!currentUser){location.href=`login.html?next=${encodeURIComponent(page+location.search)}`;return false}if(currentProfile?.account_type!==role){message(`This page is for ${role} accounts.`,'error');document.querySelectorAll('main form,main .dashboard,main .actions,main table').forEach(e=>e.classList.add('hidden'));return false}return true}
async function register(form){const f=new FormData(form),type=f.get('account_type');const{data,error}=await supabase.auth.signUp({email:f.get('email'),password:f.get('password'),options:{data:{full_name:f.get('full_name'),account_type:type}}});if(error)throw error;if(data.session)location.href=type==='business'?'business-profile.html':'supplier-profile.html';else{form.reset();message('Account created. Check your email to confirm it, then log in.')}}
async function login(form){const f=new FormData(form);const{data,error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)throw error;const{data:p}=await supabase.from('profiles').select('account_type').eq('id',data.user.id).single();location.href=new URLSearchParams(location.search).get('next')||(p?.account_type==='business'?'business-dashboard.html':'supplier-dashboard.html')}
async function saveProfile(form,type){const f=new FormData(form),payload={user_id:currentUser.id,company_name:f.get('company_name'),address:f.get('address'),phone:f.get('phone'),contact_email:f.get('contact_email'),description:f.get('description')};if(type==='supplier')payload.industry_category=f.get('industry_category');const{error}=await supabase.from(`${type}_profiles`).upsert(payload,{onConflict:'user_id'});if(error)throw error;message('Profile saved.')}
async function loadProfile(form,type){const{data}=await supabase.from(`${type}_profiles`).select('*').eq('user_id',currentUser.id).maybeSingle();if(!data){form.elements.contact_email.value=currentUser.email||'';return}Object.entries(data).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v??''})}
async function createTender(form){const f=new FormData(form),doc=await upload('tender-documents',f.get('document'));const{data,error}=await supabase.from('tenders').insert({business_id:currentUser.id,title:f.get('title'),description:f.get('description'),closing_date:f.get('closing_date'),document_path:doc?.path,document_name:doc?.name}).select('id').single();if(error){if(doc)await supabase.storage.from('tender-documents').remove([doc.path]);throw error}message('Tender published.');setTimeout(()=>location.href=`tender-details.html?id=${data.id}`,500)}
async function submitBid(form){const id=new URLSearchParams(location.search).get('id');if(!id)throw new Error('No tender was selected.');const f=new FormData(form),amount=Number(String(f.get('amount')).replace(/[^0-9.]/g,''));if(!Number.isFinite(amount)||amount<=0)throw new Error('Enter a valid bid amount.');const doc=await upload('bid-documents',f.get('document'));const{error}=await supabase.from('bids').insert({tender_id:id,supplier_id:currentUser.id,amount,document_path:doc.path,document_name:doc.name});if(error){await supabase.storage.from('bid-documents').remove([doc.path]);throw error}form.reset();message('Your bid was submitted securely.')}
async function renderTenderRows(){const body=document.getElementById('tenderRows');if(!body)return;const{data,error}=await supabase.from('tenders').select('id,title,closing_date,status,business_profiles(company_name)').eq('status','open').gte('closing_date',new Date().toISOString().slice(0,10)).order('closing_date');if(error)throw error;body.innerHTML=data.length?data.map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.business_profiles?.company_name||'Business')}</td><td>${fmtDate(t.closing_date)}</td><td><span class="badge">Open</span></td><td><a class="btn" href="tender-details.html?id=${t.id}">View Details</a></td></tr>`).join(''):'<tr><td colspan="5">No open tenders found.</td></tr>'}
async function renderDetails(){const box=document.getElementById('tenderDetails');if(!box)return;const id=new URLSearchParams(location.search).get('id'),{data:t,error}=await supabase.from('tenders').select('*,business_profiles(company_name)').eq('id',id).single();if(error){box.textContent='Tender not found.';return}const url=await signedUrl('tender-documents',t.document_path),open=t.status==='open'&&t.closing_date>=new Date().toISOString().slice(0,10);box.innerHTML=`<h2>${esc(t.title)}</h2><p><strong>Business:</strong> ${esc(t.business_profiles?.company_name||'Business')}</p><p><strong>Closing Date:</strong> ${fmtDate(t.closing_date)}</p><p>${esc(t.description)}</p>${url?`<p><strong>Supporting Document:</strong> <a href="${url}" target="_blank" rel="noopener">${esc(t.document_name)}</a></p>`:''}<div class="actions">${open?`<a class="btn" href="submit-bid.html?id=${t.id}">Submit Bid</a>`:''}<a class="btn gold" href="tenders.html">Back to Tenders</a></div>`}
async function renderMyTenders(){const body=document.getElementById('myTenderRows');if(!body)return;const{data,error}=await supabase.from('tenders').select('id,title,closing_date,status,bids(count)').eq('business_id',currentUser.id).order('created_at',{ascending:false});if(error)throw error;body.innerHTML=data.length?data.map(t=>`<tr><td>${esc(t.title)}</td><td>${fmtDate(t.closing_date)}</td><td>${t.bids?.[0]?.count||0}</td><td><a class="btn" href="view-bids.html?id=${t.id}">View Bids</a></td></tr>`).join(''):'<tr><td colspan="4">You have not published a tender yet.</td></tr>';const s=document.querySelectorAll('.stat strong'),bc=data.reduce((n,t)=>n+(t.bids?.[0]?.count||0),0);if(s.length===3){s[0].textContent=data.length;s[1].textContent=bc;s[2].textContent=data.filter(t=>t.status==='open').length}}
async function renderBids(){const body=document.getElementById('bidRows');if(!body)return;const id=new URLSearchParams(location.search).get('id'),{data,error}=await supabase.from('bids').select('amount,created_at,document_path,document_name,supplier_profiles(company_name)').eq('tender_id',id).order('created_at');if(error)throw error;const rows=await Promise.all(data.map(async b=>{const url=await signedUrl('bid-documents',b.document_path);return`<tr><td>${esc(b.supplier_profiles?.company_name||'Supplier')}</td><td>${money(b.amount)}</td><td>${new Date(b.created_at).toLocaleDateString('en-JM')}</td><td>${url?`<a href="${url}" target="_blank" rel="noopener">${esc(b.document_name)}</a>`:'Unavailable'}</td></tr>`}));body.innerHTML=rows.join('')||'<tr><td colspan="4">No bids have been submitted.</td></tr>'}
async function renderSupplierStats(){if(page!=='supplier-dashboard.html')return;const today=new Date().toISOString().slice(0,10),rs=await Promise.all([supabase.from('tenders').select('*',{count:'exact',head:true}).eq('status','open').gte('closing_date',today),supabase.from('bids').select('*',{count:'exact',head:true}).eq('supplier_id',currentUser.id),supabase.from('supplier_profiles').select('*',{count:'exact',head:true}).eq('user_id',currentUser.id)]),s=document.querySelectorAll('.stat strong');rs.forEach((r,i)=>{if(s[i])s[i].textContent=r.count||0})}
function prepareForms(){const specs={'register.html':['register',['full_name','email','password','account_type']],'login.html':['login',['email','password']],'business-profile.html':['business-profile',['company_name','address','phone','contact_email','description']],'supplier-profile.html':['supplier-profile',['company_name','address','industry_category','phone','contact_email','description']],'create-tender.html':['create-tender',['title','description','closing_date','document']],'submit-bid.html':['submit-bid',['amount','document']]};const spec=specs[page],form=document.querySelector('form[data-demo],form[data-action]');if(!spec||!form)return;form.dataset.action=spec[0];[...form.querySelectorAll('input,select,textarea')].forEach((el,i)=>{el.name=spec[1][i];if(page==='register.html'&&el.name==='account_type')[...el.options].forEach(o=>o.value=o.textContent.toLowerCase())});form.querySelector('button')?.setAttribute('type','submit')}
function wireForms(){document.querySelectorAll('form[data-action]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();busy(form,true);try{const a=form.dataset.action;if(a==='register')await register(form);else if(a==='login')await login(form);else if(a==='business-profile')await saveProfile(form,'business');else if(a==='supplier-profile')await saveProfile(form,'supplier');else if(a==='create-tender')await createTender(form);else if(a==='submit-bid')await submitBid(form)}catch(error){message(error.message||'Something went wrong.','error')}finally{busy(form,false)}}))}
async function init(){setYear();prepareForms();if(!configured()){message('Supabase is not configured yet. Add your project URL and anon key in supabase-config.js.','error');return}try{const{createClient}=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm');supabase=createClient(config.url,config.anonKey);await getSession();updateAuthUi();if(!enforceAccess())return;wireForms();const b=document.querySelector('form[data-action="business-profile"]'),s=document.querySelector('form[data-action="supplier-profile"]');if(b)await loadProfile(b,'business');if(s)await loadProfile(s,'supplier');await Promise.all([renderTenderRows(),renderDetails(),renderMyTenders(),renderBids(),renderSupplierStats()])}catch(error){message(error.message||'The application could not connect to Supabase.','error')}}
document.addEventListener('DOMContentLoaded',init);
